BLUR_CONST = 3
ADAPTIVE_THRESH_AREA = 11; ADAPTIVE_THRESH_CONST = 2; COMPARISON_VALUE = 7
THRESHOLD_VAL = 220; THRESHOLD_MAX = 255
MIN_CONTOUR_POINTS = 250; CONTOUR_WEIGHT = 1
EPSILON = 0.01
HIRAR_LEGEND={"NEXT":0, "PREV":1, "FIRST":2, "PARENT":3}
BOUND_LEGEND={"X":0,"Y":1,"WIDTH":2,"HEIGHT":3}
# IMAGE_PATH = 'image.png'
IMAGE_PATH = 'utils/m_2_inverted.png'
# IMAGE_PATH = 'utils/m_3.png'
WINDOW_WIDTH = 800
FISH_SIZE = (15,15); FISH_COLOR = (255,255,255)

