BLUR_SIZE = (21, 21)
ADAPTIVE_THRESH_AREA = 11; ADAPTIVE_THRESH_CONST = 2
THRESHOLD_VAL = 100; THRESHOLD_MAX = 255
MIN_CONTOUR_POINTS = 400; MIN_FRAME_CONTENT_PARTITION = 7
SAME_CONTOUR_THRESHOLD = 0.92
HIRAR_LEGEND={"NEXT":0, "PREV":1, "FIRST":2, "PARENT":3}
BOUND_LEGEND={"X":0,"Y":1,"WIDTH":2,"HEIGHT":3}
WINDOW_WIDTH = 1200; IMAGE_RESIZE_WIDTH = 600
FISH_SIZE = (20,20); FISH_COLOR = (255,255,255); FREE_AREA_FOR_FISH = 100; FISH_BORDER = 3
MAX_PLACEMENT_ATTAMPTS = 5
TRIM_EDGES_CONST = 7
INTERNAL_SPRITE_IMG = 'utils\\images\\location.png'